### ISSUE TITLE
SQL schema size limit

### ISSUE THREAD

**Issue by binary64** [woniesong92/talktosql#1]
Hi, Your app looks fantastic! Thank you so much. I have a simple question, which is what is the limit for the size of the schema, in bytes or tokens? I have a large schema ~2MB

Many thanks and your open source is very much appriciated.

**Comment by woniesong92** [comment]
I'm glad you find it helpful! That's such a good question. The max number of tokens is different depending on what model you choose to use. For example, GPT-4 allows 8k tokens max while `GPT-4-32k` allows 32k tokens max. This should go pretty far (~16 pages and 64 pages respectively). Try running `talktosql learn` and see how big the schema info file is!

**Comment by OneTop4458** [comment]
현재 [gpt-4-32k](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4)는 사용 불가입니다.

gpt-3.5-turbo-16k가 2023.07.17. 기준 일반인이 쓸 수 있는 max token이 가장 높은 모델인데
이것도 테이블 10개 정도 있는 나름 작은 db에 사용해 보니 토큰 초과로 안되는군요 ㅠㅠ..

gpt-4-32k 모델이 다시 풀리기 전까지는 아주 작은 토이프로젝트 db 정도에만 쓸 수 있을 것 같습니다..
