### ISSUE TITLE
Can you limit the generated sql to be only 'SELECT syntax' ? 

### ISSUE THREAD

**Issue by leo6104** [woniesong92/talktosql#2]
Thanks for awesome project. We want to apply your project&idea in our internal Business Insight dashboard (as Chat). 

I think it would be great if it only run SELECT syntax in `handle_ask_command` function. 

There is no limit to execute query so it can cause unintentional changes in database.

**Comment by woniesong92** [comment]
Hey I'm glad you find it useful. You can update the prompt to force it to stick to SELECT queries. Start by adding `Only use SELECT queries and return an error if impossible` to the current prompt. Here's [the prompt](https://github.com/woniesong92/talktosql/blob/main/src/talktosql/talktosql.py#L41-L49)!
